# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e39a4b89c522fb7ec534ad58ef6cd635a4fba7e671382cab8f2b85c76cecde5527a960f25542d639b55e5980e9b38103c2db6f1fd3167a8352cba874d6d389

test:
  secret_key_base: 4dd5774504cefa7be34cefdd1d628f032fee79877e56ccacbd4965eb03613f0c3e1bc729e7e73a28e1d26338dbfcae22e90809f7ca3f827a28b131fb85c9a90f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
